export enum IS_STARTED_MINTING {
  NOT_STARTED = 0,
  LIVE = 1
}

export enum MINTING_STATUS {
  WALLET_NOT_CONNECTED = 0,
  WALLET_CONNECTING = 1,
  LOADING = 2,
  ELIGIBLE = 3,
  NOT_ELIGIBLE = 4,
  MINTING = 5,
  MINTING_MAXIMUM = 6,
  SOLD_OUT = 7,
  ENDED = 8,
  PHASE_SOLD_OUT = 9
}
